// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtsnAMgsLz4lGbiHEBoPNzqAa9u3miq2c',
    appId: '1:460363291466:web:364c4dde70ccc7cba03fb3',
    messagingSenderId: '460363291466',
    projectId: 'easacc-task-41def',
    authDomain: 'easacc-task-41def.firebaseapp.com',
    storageBucket: 'easacc-task-41def.firebasestorage.app',
    measurementId: 'G-BWYVSJHRLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdHSbHYwhnTh5mIJzBxcC3Pb2cSPsQTgg',
    appId: '1:460363291466:android:3b090e1462f79d10a03fb3',
    messagingSenderId: '460363291466',
    projectId: 'easacc-task-41def',
    storageBucket: 'easacc-task-41def.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6z8yk_citlP5_l3KXgmmDtDgE8rUC6K4',
    appId: '1:460363291466:ios:52b0599b33618a22a03fb3',
    messagingSenderId: '460363291466',
    projectId: 'easacc-task-41def',
    storageBucket: 'easacc-task-41def.firebasestorage.app',
    iosClientId: '460363291466-hq5v8lebi60ot9apqeq5ai4iolsgki72.apps.googleusercontent.com',
    iosBundleId: 'com.example.easaccTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6z8yk_citlP5_l3KXgmmDtDgE8rUC6K4',
    appId: '1:460363291466:ios:52b0599b33618a22a03fb3',
    messagingSenderId: '460363291466',
    projectId: 'easacc-task-41def',
    storageBucket: 'easacc-task-41def.firebasestorage.app',
    iosClientId: '460363291466-hq5v8lebi60ot9apqeq5ai4iolsgki72.apps.googleusercontent.com',
    iosBundleId: 'com.example.easaccTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtsnAMgsLz4lGbiHEBoPNzqAa9u3miq2c',
    appId: '1:460363291466:web:c117d7f04d64df8ea03fb3',
    messagingSenderId: '460363291466',
    projectId: 'easacc-task-41def',
    authDomain: 'easacc-task-41def.firebaseapp.com',
    storageBucket: 'easacc-task-41def.firebasestorage.app',
    measurementId: 'G-3BVVZDESXE',
  );
}
